service: auth-server

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

functions:
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http: 
          path: api/token/{code}
          method: get